//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.08 at 06:55:36 PM EEST 
//


package ohloh_stat.entity.jaxb.all;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="items_returned" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="items_available" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="first_item_position" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="result">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="project" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="html_url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="created_at" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                             &lt;element name="updated_at" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="homepage_url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="download_url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="url_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="user_count" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="average_rating" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="rating_count" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="review_count" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                             &lt;element name="analysis_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="tags" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="tag" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="licenses">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="license" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="nice_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="project_activity_index">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "status",
    "itemsReturned",
    "itemsAvailable",
    "firstItemPosition",
    "result"
})
@XmlRootElement(name = "response")
public class Response {

    @XmlElement(required = true)
    protected String status;
    @XmlElement(name = "items_returned")
    protected byte itemsReturned;
    @XmlElement(name = "items_available")
    protected int itemsAvailable;
    @XmlElement(name = "first_item_position")
    protected byte firstItemPosition;
    @XmlElement(required = true)
    protected Response.Result result;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the itemsReturned property.
     * 
     */
    public byte getItemsReturned() {
        return itemsReturned;
    }

    /**
     * Sets the value of the itemsReturned property.
     * 
     */
    public void setItemsReturned(byte value) {
        this.itemsReturned = value;
    }

    /**
     * Gets the value of the itemsAvailable property.
     * 
     */
    public int getItemsAvailable() {
        return itemsAvailable;
    }

    /**
     * Sets the value of the itemsAvailable property.
     * 
     */
    public void setItemsAvailable(int value) {
        this.itemsAvailable = value;
    }

    /**
     * Gets the value of the firstItemPosition property.
     * 
     */
    public byte getFirstItemPosition() {
        return firstItemPosition;
    }

    /**
     * Sets the value of the firstItemPosition property.
     * 
     */
    public void setFirstItemPosition(byte value) {
        this.firstItemPosition = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link Response.Result }
     *     
     */
    public Response.Result getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response.Result }
     *     
     */
    public void setResult(Response.Result value) {
        this.result = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="project" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="html_url" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="created_at" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                   &lt;element name="updated_at" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="homepage_url" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="download_url" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="url_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="user_count" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="average_rating" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="rating_count" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="review_count" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="analysis_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="tags" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="tag" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="licenses">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="license" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                       &lt;element name="nice_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="project_activity_index">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "project"
    })
    public static class Result {

        protected List<Response.Result.Project> project;

        /**
         * Gets the value of the project property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the project property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProject().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Response.Result.Project }
         * 
         * 
         */
        public List<Response.Result.Project> getProject() {
            if (project == null) {
                project = new ArrayList<Response.Result.Project>();
            }
            return this.project;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="html_url" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="created_at" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *         &lt;element name="updated_at" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="homepage_url" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="download_url" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="url_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="user_count" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="average_rating" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="rating_count" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="review_count" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="analysis_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="tags" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="tag" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="licenses">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="license" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="nice_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="project_activity_index">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "id",
            "name",
            "url",
            "htmlUrl",
            "createdAt",
            "updatedAt",
            "description",
            "homepageUrl",
            "downloadUrl",
            "urlName",
            "userCount",
            "averageRating",
            "ratingCount",
            "reviewCount",
            "analysisId",
            "tags",
            "licenses",
            "projectActivityIndex"
        })
        public static class Project {

            protected int id;
            @XmlElement(required = true)
            protected String name;
            @XmlElement(required = true)
            protected String url;
            @XmlElement(name = "html_url", required = true)
            protected String htmlUrl;
            @XmlElement(name = "created_at", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar createdAt;
            @XmlElement(name = "updated_at", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar updatedAt;
            @XmlElement(required = true)
            protected String description;
            @XmlElement(name = "homepage_url", required = true)
            protected String homepageUrl;
            @XmlElement(name = "download_url", required = true)
            protected String downloadUrl;
            @XmlElement(name = "url_name", required = true)
            protected String urlName;
            @XmlElement(name = "user_count")
            protected byte userCount;
            @XmlElement(name = "average_rating", required = true)
            protected String averageRating;
            @XmlElement(name = "rating_count")
            protected byte ratingCount;
            @XmlElement(name = "review_count")
            protected byte reviewCount;
            @XmlElement(name = "analysis_id")
            protected int analysisId;
            protected Response.Result.Project.Tags tags;
            @XmlElement(required = true)
            protected Response.Result.Project.Licenses licenses;
            @XmlElement(name = "project_activity_index", required = true)
            protected Response.Result.Project.ProjectActivityIndex projectActivityIndex;

            /**
             * Gets the value of the id property.
             * 
             */
            public int getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             */
            public void setId(int value) {
                this.id = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the url property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUrl() {
                return url;
            }

            /**
             * Sets the value of the url property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUrl(String value) {
                this.url = value;
            }

            /**
             * Gets the value of the htmlUrl property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHtmlUrl() {
                return htmlUrl;
            }

            /**
             * Sets the value of the htmlUrl property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHtmlUrl(String value) {
                this.htmlUrl = value;
            }

            /**
             * Gets the value of the createdAt property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getCreatedAt() {
                return createdAt;
            }

            /**
             * Sets the value of the createdAt property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setCreatedAt(XMLGregorianCalendar value) {
                this.createdAt = value;
            }

            /**
             * Gets the value of the updatedAt property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getUpdatedAt() {
                return updatedAt;
            }

            /**
             * Sets the value of the updatedAt property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setUpdatedAt(XMLGregorianCalendar value) {
                this.updatedAt = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the homepageUrl property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHomepageUrl() {
                return homepageUrl;
            }

            /**
             * Sets the value of the homepageUrl property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHomepageUrl(String value) {
                this.homepageUrl = value;
            }

            /**
             * Gets the value of the downloadUrl property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDownloadUrl() {
                return downloadUrl;
            }

            /**
             * Sets the value of the downloadUrl property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDownloadUrl(String value) {
                this.downloadUrl = value;
            }

            /**
             * Gets the value of the urlName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUrlName() {
                return urlName;
            }

            /**
             * Sets the value of the urlName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUrlName(String value) {
                this.urlName = value;
            }

            /**
             * Gets the value of the userCount property.
             * 
             */
            public byte getUserCount() {
                return userCount;
            }

            /**
             * Sets the value of the userCount property.
             * 
             */
            public void setUserCount(byte value) {
                this.userCount = value;
            }

            /**
             * Gets the value of the averageRating property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAverageRating() {
                return averageRating;
            }

            /**
             * Sets the value of the averageRating property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAverageRating(String value) {
                this.averageRating = value;
            }

            /**
             * Gets the value of the ratingCount property.
             * 
             */
            public byte getRatingCount() {
                return ratingCount;
            }

            /**
             * Sets the value of the ratingCount property.
             * 
             */
            public void setRatingCount(byte value) {
                this.ratingCount = value;
            }

            /**
             * Gets the value of the reviewCount property.
             * 
             */
            public byte getReviewCount() {
                return reviewCount;
            }

            /**
             * Sets the value of the reviewCount property.
             * 
             */
            public void setReviewCount(byte value) {
                this.reviewCount = value;
            }

            /**
             * Gets the value of the analysisId property.
             * 
             */
            public int getAnalysisId() {
                return analysisId;
            }

            /**
             * Sets the value of the analysisId property.
             * 
             */
            public void setAnalysisId(int value) {
                this.analysisId = value;
            }

            /**
             * Gets the value of the tags property.
             * 
             * @return
             *     possible object is
             *     {@link Response.Result.Project.Tags }
             *     
             */
            public Response.Result.Project.Tags getTags() {
                return tags;
            }

            /**
             * Sets the value of the tags property.
             * 
             * @param value
             *     allowed object is
             *     {@link Response.Result.Project.Tags }
             *     
             */
            public void setTags(Response.Result.Project.Tags value) {
                this.tags = value;
            }

            /**
             * Gets the value of the licenses property.
             * 
             * @return
             *     possible object is
             *     {@link Response.Result.Project.Licenses }
             *     
             */
            public Response.Result.Project.Licenses getLicenses() {
                return licenses;
            }

            /**
             * Sets the value of the licenses property.
             * 
             * @param value
             *     allowed object is
             *     {@link Response.Result.Project.Licenses }
             *     
             */
            public void setLicenses(Response.Result.Project.Licenses value) {
                this.licenses = value;
            }

            /**
             * Gets the value of the projectActivityIndex property.
             * 
             * @return
             *     possible object is
             *     {@link Response.Result.Project.ProjectActivityIndex }
             *     
             */
            public Response.Result.Project.ProjectActivityIndex getProjectActivityIndex() {
                return projectActivityIndex;
            }

            /**
             * Sets the value of the projectActivityIndex property.
             * 
             * @param value
             *     allowed object is
             *     {@link Response.Result.Project.ProjectActivityIndex }
             *     
             */
            public void setProjectActivityIndex(Response.Result.Project.ProjectActivityIndex value) {
                this.projectActivityIndex = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="license" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="nice_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "content"
            })
            public static class Licenses {

                @XmlElementRef(name = "license", type = JAXBElement.class, required = false)
                @XmlMixed
                protected List<Serializable> content;

                /**
                 * Gets the value of the content property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the content property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getContent().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * {@link JAXBElement }{@code <}{@link Response.Result.Project.Licenses.License }{@code >}
                 * 
                 * 
                 */
                public List<Serializable> getContent() {
                    if (content == null) {
                        content = new ArrayList<Serializable>();
                    }
                    return this.content;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="nice_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "name",
                    "niceName"
                })
                public static class License {

                    @XmlElement(required = true)
                    protected String name;
                    @XmlElement(name = "nice_name", required = true)
                    protected String niceName;

                    /**
                     * Gets the value of the name property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getName() {
                        return name;
                    }

                    /**
                     * Sets the value of the name property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setName(String value) {
                        this.name = value;
                    }

                    /**
                     * Gets the value of the niceName property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getNiceName() {
                        return niceName;
                    }

                    /**
                     * Sets the value of the niceName property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setNiceName(String value) {
                        this.niceName = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value",
                "description"
            })
            public static class ProjectActivityIndex {

                protected byte value;
                @XmlElement(required = true)
                protected String description;

                /**
                 * Gets the value of the value property.
                 * 
                 */
                public byte getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 */
                public void setValue(byte value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the description property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDescription() {
                    return description;
                }

                /**
                 * Sets the value of the description property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDescription(String value) {
                    this.description = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="tag" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "tag"
            })
            public static class Tags {

                protected List<String> tag;

                /**
                 * Gets the value of the tag property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the tag property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getTag().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link String }
                 * 
                 * 
                 */
                public List<String> getTag() {
                    if (tag == null) {
                        tag = new ArrayList<String>();
                    }
                    return this.tag;
                }

            }

        }

    }

}
